/**
 * 
 */
package com.tarang.ewallet.reports.util;

/**
 * @author  : prasadj
 * @date    : Feb 4, 2013
 * @time    : 4:21:59 PM
 * @version : 1.0.0
 * @comments: 
 *
 */
public interface ReportConstants {

	// Customer Reports
	Long CUSTOMER_LAST_N_TRANSACTIONS = 1L;
	
	Long CUSTOMER_MERCHANT_WISE_TRANSACTION = 2L;
	
	Long CUSTOMER_RECEIVE_MONEY_TRANSACTION = 3L;
	
	Long CUSTOMER_SEND_MONEY_TRANSACTION = 4L;
	
	Long CUSTOMER_REQUEST_FAILS = 5L;
	
	Long CUSTOMER_FAILED_TRANSACTION = 6L;
	
	Long CUSTOMER_DISPUTED_TRANSACTION = 27L;
	

	// Merchant Reports
	Long MERCHANT_LAST_N_TRANSACTIONS = 7L;
	
	Long MERCHANT_RECEIVE_MONEY_TRANSACTION = 8L;
	
	Long MERCHANT_SEND_MONEY_TRANSACTION = 9L;

	Long MERCHANT_CUSTOMER_WISE_TRANSACTION = 10L;

	Long MERCHANT_FAILED_TRANSACTION = 11L;
	
	Long MERCHANT_COMMISSION_SUMMARY = 25L;
	
	Long MERCHANT_DISPUTED_TRANSACTION = 26L;
	
	// Admin Reports

	Long USER_LAST_N_TRANSACTIONS = 12L;

	Long USER_CUSTOMER_WISE_TRANSACTION = 13L;
	
	Long USER_MERCHANT_WISE_TRANSACTION = 14L;

	Long COMMISSION_SUMMARY = 15L;
	
	Long USER_CUSTOMER_BALANCES = 16L;
	
	Long USER_MERCHANT_BALANCES = 17L;
	
	Long USER_CUSTOMER_HAVING_OVER_LIMIT = 18L;
	
	Long USER_CUSTOMER_REQUEST_FAILS = 19L;

	Long USER_CUSTOMER_FAILED_TRANSACTION = 20L;

	Long USER_DORMANT_ACCOUNTS = 21L;
	
	Long USER_DISPUTED_TRANSACTION = 22L;
	
	Long LIST_OF_ACCOUNT_NOT_USED_IN_X_TIME = 23L;
	
	Long FRAUDULENT_TRANSACTION = 24L;

}
